# Site settings
title: Faris
email: faris@duck.com
description: An Esoteric Garden
baseurl: "/frshbb.github.io"
url: "https://manifoldfrs.github.io"
# enforce_ssl: "https://manifoldfrs.github.io/frshbb.github.io/" # Removed: GitHub Pages enforces SSL. jekyll-seo-tag handles protocol.
lang: en_US
timezone: UTC

# Author information
author:
  name: Faris Habib
  bio: >-
  location: Nomad
  avatar: /assets/images/chicago_talk_2024.jpg

# Social media links
social:
  github: manifoldfrs
  twitter: frshbb
  linkedin: farishabib
  instagram: frs_hbb
  substack: frshbb

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  # For lazy loading images in Markdown:
  # Add attributes directly in Markdown: ![alt text](image.jpg){: loading="lazy"}
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      share: true
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"
      share: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - LICENSE
  - README.md
  - prompts
  - config.yml
  - .github/
  - .cursorrules
  - frshbb.github.io.code-workspace

# Nord theme color scheme
nord_colors:
  dark_bg: "#2E3440"
  darker_bg: "#3B4252"
  text: "#ECEFF4"
  primary: "#88C0D0"
  secondary: "#A3BE8C"
  tertiary: "#EBCB8B"
  alert: "#BF616A"
  links: "#5E81AC"
